name: Build and Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build ${{ matrix.binary_target }}
    runs-on: ${{ matrix.os }}
    env:
      BINARY_NAME: rust_github_action
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            binary_target: x86_64-unknown-linux-musl
          - os: ubuntu-latest
            binary_target: x86_64-unknown-linux-gnu
          - os: windows-latest
            binary_target: x86_64-pc-windows-msvc
          - os: macos-latest
            binary_target: x86_64-apple-darwin
          - os: macos-latest
            binary_target: aarch64-apple-darwin

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install musl tools
        if: matrix.binary_target == 'x86_64-unknown-linux-musl'
        run: sudo apt-get install -y musl-tools

      - name: Install target
        run: rustup target add ${{ matrix.binary_target }}

      - name: Build binary
        run: |
          cargo build --release --target ${{ matrix.binary_target }}

      - name: Set archive name
        id: archive
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            echo "ARCHIVE_NAME=${{ env.BINARY_NAME }}-v${{ github.ref_name }}-${{ matrix.binary_target }}.zip" >> $GITHUB_ENV
          else
            echo "ARCHIVE_NAME=${{ env.BINARY_NAME }}-v${{ github.ref_name }}-${{ matrix.binary_target }}.tar.gz" >> $GITHUB_ENV
          fi

      - name: Prepare binary (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          cd target/${{ matrix.binary_target }}/release
          tar -czf ../../../${{ env.ARCHIVE_NAME }} ${{ env.BINARY_NAME }}
          cd -

      - name: Prepare binary (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          cd target/${{ matrix.binary_target }}/release
          $BINARY_NAME = "${{ env.BINARY_NAME }}.exe"
          Compress-Archive -Path $BINARY_NAME -DestinationPath ../../../${{ env.ARCHIVE_NAME }}
          cd -

      - name: Upload Release Asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.ARCHIVE_NAME }}
          asset_name: ${{ env.ARCHIVE_NAME }}
          tag: ${{ github.ref }}
          overwrite: true
